-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=nep-vm3.llnl.gov;sid=dccdb;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



-- Oracle package 'TOX' declaration, please edit to match PostgreSQL syntax.

DROP SCHEMA IF EXISTS tox CASCADE;
CREATE SCHEMA tox;


/*========================================================================*/
CREATE OR REPLACE FUNCTION tox.begin_spool () RETURNS VOID AS $body$
DECLARE

		/*-----------------------*/
		/*=======================*/
		
BEGIN
		/*=======================*/
			SELECT
				nextval('key')
			INTO STRICT
				g_spool_key
			;
		/*=======================*/
		END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION tox.begin_spool () FROM PUBLIC;
	/*========================================================================*/
CREATE OR REPLACE FUNCTION tox.into_spool ( in_txt spool.txt%TYPE ) RETURNS VOID AS $body$
DECLARE

		/*-----------------------*/
		/*=======================*/
		
BEGIN
		/*=======================*/
			INSERT INTO
				spool
			VALUES (
				g_spool_key,
				in_txt,
				nextval('seq')
				);
		/*=======================*/
		END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION tox.into_spool ( in_txt spool.txt%TYPE ) FROM PUBLIC;
	/*========================================================================*/
CREATE OR REPLACE FUNCTION tox.reset_spool () RETURNS VOID AS $body$
DECLARE

		/*-----------------------*/
		/*=======================*/
		
BEGIN
		/*=======================*/
			DELETE
				FROM spool
			WHERE
				key = g_spool_key;
			COMMIT;
			PERFORM tox.begin_spool();
		/*=======================*/
		END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION tox.reset_spool () FROM PUBLIC;
	/*========================================================================*/
CREATE OR REPLACE FUNCTION tox.end_spool () RETURNS T_SPOOL AS $body$
DECLARE

		/*-----------------------*/
		v_spool t_spool;
		/*=======================*/
		
BEGIN
		/*=======================*/
		/*-----------------------*/
			COMMIT;
			OPEN v_spool FOR
				SELECT
					*
				FROM
					spool
				WHERE
					key = g_spool_key
				ORDER BY
					seq;
			RETURN v_spool;
		/*=======================*/
		END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION tox.end_spool () FROM PUBLIC;
	/*========================================================================*/
CREATE OR REPLACE FUNCTION tox.timestamp () RETURNS varchar AS $body$
DECLARE

		/*-----------------------*/
		v_result varchar(14);
		/*=======================*/
		
BEGIN
		/*=======================*/
			SELECT
				TO_CHAR(clock_timestamp(),'YYYYMMDDHH24MISS')
			INTO STRICT
				v_result
			;
			RETURN v_result;
		/*=======================*/
		END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION tox.timestamp () FROM PUBLIC;
	/*========================================================================*/
CREATE OR REPLACE FUNCTION tox.encode ( in_original text ) RETURNS varchar AS $body$
DECLARE

		/*-----------------------*/
		v_result varchar(2048);
		/*=======================*/
		
BEGIN
		/*=======================*/
		IF (in_original IS NOT NULL) THEN
			v_result:= REPLACE(in_original,'&','&amp;');
			v_result:= REPLACE(v_result,'"','&quot;');
			v_result:= REPLACE(v_result,'<','&lt;');
			v_result:= REPLACE(v_result,'>','&gt;');
		ELSE
			v_result:= NULL;
		END IF;
		/*-----------------------*/
		RETURN v_result;
		/*=======================*/
		END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION tox.encode ( in_original text ) FROM PUBLIC;
-- End of Oracle package 'TOX' declaration

