-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=nep-vm3.llnl.gov;sid=dccdb;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON


CREATE UNLOGGED TABLE tox.spool (
	key bigint NOT NULL,
	txt text,
	seq bigint NOT NULL
) ;
